{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "executionInfo": {
     "elapsed": 11739,
     "status": "ok",
     "timestamp": 1779778996387,
     "user": {
      "displayName": "Vesuke",
      "userId": "16595294488996971590"
     },
     "user_tz": -180
    },
    "id": "kx4Wtx41jAFo",
    "outputId": "e7023537-b4db-404e-afcb-8cab0d9d4ac7"
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "--- TEST 1: Product Inquiry ---\n",
      "\n",
      "👤 CUSTOMER: Do you have any black hoodies in stock? And how much are they?\n",
      "\n",
      "⚙️ SYSTEM: Searching catalog for 'black hoodie'...\n",
      "🤖 AGENT: Yes, we do! We have the Black Hoodie in stock. It is priced at $45.00, and we currently have 12 available.\n",
      "\n",
      "--- TEST 2: Order Status ---\n",
      "\n",
      "👤 CUSTOMER: Where is my stuff? My order number is ORD-999.\n",
      "\n",
      "⚙️ SYSTEM: Looking up order ORD-999...\n",
      "🤖 AGENT: Your order ORD-999 is currently processing. We will update you as soon as it ships!\n",
      "\n",
      "--- TEST 3: Asking Price ---\n",
      "\n",
      "👤 CUSTOMER: Hello, I would like to inquire how much 5 Coffee Mugs cost to buy?\n",
      "\n",
      "⚙️ SYSTEM: Searching catalog for 'Coffee Mug'...\n",
      "🤖 AGENT: Hello! \n",
      "\n",
      "A single Coffee Mug costs $15.00. Therefore, 5 Coffee Mugs would cost a total of $75.00. \n",
      "\n",
      "We currently have 19 in stock, so they are available to order! Let me know if you would like help with anything else.\n",
      "\n",
      "--- TEST 4: Asking Stocks ---\n",
      "\n",
      "👤 CUSTOMER: Greetings, How many Black hoodies and Coffee Mugs are there?\n",
      "\n",
      "⚙️ SYSTEM: Searching catalog for 'Black hoodie'...\n",
      "\n",
      "⚙️ SYSTEM: Searching catalog for 'Coffee Mug'...\n",
      "🤖 AGENT: Greetings! We currently have 12 Black Hoodies and 19 Coffee Mugs in stock. \n",
      "\n",
      "Please let me know if you have any other questions or if you'd like help placing an order!\n"
     ]
    }
   ],
   "source": [
    "from google import genai\n",
    "\n",
    "from google.genai import types\n",
    "\n",
    "\n",
    "# Initialize your client\n",
    "\n",
    "client = genai.Client(api_key=\"YOUR-API-KEY-HERE\")\n",
    "\n",
    "\n",
    "# --- 1. THE MOCK DATABASE ---\n",
    "\n",
    "# This simulates an e-commerce backend\n",
    "\n",
    "product_database = {\n",
    "\n",
    "    \"SKU-101\": {\"name\": \"Black Hoodie\", \"price\": 45.00, \"stock\": 12},\n",
    "\n",
    "    \"SKU-102\": {\"name\": \"Coffee Mug\", \"price\": 15.00, \"stock\": 19},\n",
    "\n",
    "}\n",
    "\n",
    "\n",
    "order_database = {\n",
    "\n",
    "    \"ORD-888\": {\"status\": \"Shipped\", \"item\": \"SKU-101\", \"customer_email\": \"test@example.com\"},\n",
    "\n",
    "    \"ORD-999\": {\"status\": \"Processing\", \"item\": \"SKU-102\", \"customer_email\": \"hello@world.com\"}\n",
    "\n",
    "}\n",
    "\n",
    "\n",
    "# --- 2. THE TOOLS (Your Agent's Hands) ---\n",
    "\n",
    "\n",
    "def get_product_info(product_name: str) -> str:\n",
    "\n",
    "    \"\"\"Searches the catalog for a product and returns price and stock levels.\"\"\"\n",
    "\n",
    "    print(f\"\\n⚙️ SYSTEM: Searching catalog for '{product_name}'...\")\n",
    "\n",
    "\n",
    "\n",
    "    # Simple search logic\n",
    "\n",
    "    for sku, details in product_database.items():\n",
    "\n",
    "        if product_name.lower() in details[\"name\"].lower():\n",
    "\n",
    "            if details[\"stock\"] > 0:\n",
    "\n",
    "                return f\"Found {details['name']}. Price is ${details['price']}. We have {details['stock']} in stock.\"\n",
    "\n",
    "            else:\n",
    "\n",
    "                return f\"Found {details['name']}, but it is currently out of stock.\"\n",
    "\n",
    "\n",
    "\n",
    "    return \"Product not found in our catalog.\"\n",
    "\n",
    "\n",
    "def check_order_status(order_id: str) -> str:\n",
    "\n",
    "    \"\"\"Checks the shipping status of a specific order ID.\"\"\"\n",
    "\n",
    "    print(f\"\\n⚙️ SYSTEM: Looking up order {order_id}...\")\n",
    "\n",
    "\n",
    "\n",
    "    order = order_database.get(order_id)\n",
    "\n",
    "    if order:\n",
    "\n",
    "        return f\"Order {order_id} is currently: {order['status']}.\"\n",
    "\n",
    "    return \"Order ID not found. Please verify the number.\"\n",
    "\n",
    "\n",
    "# --- 3. THE AGENT SETUP ---\n",
    "\n",
    "\n",
    "def run_ecommerce_agent(user_message):\n",
    "\n",
    "    print(f\"\\n👤 CUSTOMER: {user_message}\")\n",
    "\n",
    "\n",
    "\n",
    "    # We give the agent specific instructions on how to behave\n",
    "\n",
    "    system_instruction = \"\"\"\n",
    "\n",
    "    You are a helpful customer service agent for an e-commerce store.\n",
    "\n",
    "    Always be polite. Use your tools to look up information before answering.\n",
    "\n",
    "    If an item is out of stock, apologize and suggest they check back later.\n",
    "\n",
    "    \"\"\"\n",
    "\n",
    "\n",
    "\n",
    "    chat = client.chats.create(\n",
    "\n",
    "        model='gemini-3.5-flash',\n",
    "\n",
    "        config=types.GenerateContentConfig(\n",
    "\n",
    "            system_instruction=system_instruction,\n",
    "\n",
    "            tools=[get_product_info, check_order_status],\n",
    "\n",
    "            temperature=0.2 # Keeps the agent focused and less \"creative\" with facts\n",
    "\n",
    "        )\n",
    "\n",
    "    )\n",
    "\n",
    "\n",
    "\n",
    "    response = chat.send_message(user_message)\n",
    "\n",
    "    print(f\"🤖 AGENT: {response.text}\")\n",
    "\n",
    "\n",
    "# --- LET'S TEST THE LOGIC ---\n",
    "\n",
    "print(\"--- TEST 1: Product Inquiry ---\")\n",
    "\n",
    "run_ecommerce_agent(\"Do you have any black hoodies in stock? And how much are they?\")\n",
    "\n",
    "print(\"\\n--- TEST 2: Order Status ---\")\n",
    "\n",
    "run_ecommerce_agent(\"Where is my stuff? My order number is ORD-999.\")\n",
    "\n",
    "print(\"\\n--- TEST 3: Asking Price ---\")\n",
    "\n",
    "run_ecommerce_agent(\"Hello, I would like to inquire how much 5 Coffee Mugs cost to buy?\")\n",
    "\n",
    "print(\"\\n--- TEST 4: Asking Stocks ---\")\n",
    "\n",
    "run_ecommerce_agent(\"Greetings, How many Black hoodies and Coffee Mugs are there?\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "executionInfo": {
     "elapsed": 76,
     "status": "aborted",
     "timestamp": 1779778881354,
     "user": {
      "displayName": "Vesuke",
      "userId": "16595294488996971590"
     },
     "user_tz": -180
    },
    "id": "HHfZUVX_jXVH"
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "colab": {
   "authorship_tag": "ABX9TyNyO9TkB7fH4KYuCok+2rpi",
   "provenance": []
  },
  "kernelspec": {
   "display_name": "Python 3",
   "name": "python3"
  },
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
